### ISSUE TITLE
Dynamically resize body when open

### ISSUE THREAD

**Issue by MichaelLambert78** [artberri/sidr#270]
When close main content body= 100%
When open = sidebar 20% and main content body 80%

Any simple way to accomplish this?

**Comment by nverduin** [comment]
I'm looking to do this same thing.

**Comment by sfchang92** [comment]
I modified the main js to achieve something similar by deducting **p px** from **u.width()**, instead of 

*.css({width:u.width(),position:"absolute"})*

it becomes

*.css({width:u.width()__+"-"+p+"px"__,position:"absolute"})*

The main content width is whatever left after the default sidebar width. 
Keep in mind that the content you are looking at might move downward after opening the sidebar if the window width is already small to begin with.

**Comment by artberri** [comment]
It can not be done right now and is not going to be supported for now sorry.
