### ISSUE TITLE
bower package for version 1.2.1 was modified

### ISSUE THREAD

**Issue by tikotzky** [artberri/sidr#283]
It seems like the bower packages file tree for v1.2.1 used to have `jquery.sidr.min.js` in the root of the package distributed by bower. It looked like this.
```
.
|____.bower.json
|____component.json
|____jquery.sidr.min.js
|____README.md
|____stylesheets
| |____jquery.sidr.dark.css
| |____jquery.sidr.light.css
```

Sometime tonight the bower package for v1.2.1 was changed so that now the files are nested under `/dist`.

Just a heads up... this is a breaking change for anyone who was requiring the files directly from the fs.

As a workaround you can get the old package by updating your `bower.json` from
`"sidr": "1.2.1"`
to
`"sidr": "https://github.com/artberri/sidr-package.git#fffd6d48de7d7bd41705855d8a583c98b943bc8e",`

**Comment by artberri** [comment]
You are right.

Sorry because of the breaking change, but I needed to do it so now I will have a normal bower package instead of having here a submodule. 

Apart from the workaround that you give us and that is totally fine, you can also just add the `dist/`folder to your paths and it will solve the problem.

Yesterday I've updated the project after 2 years of inactivity. What I really suggest you is to update to the new 2.0.0 version that fixes several bugs: [CHANGELOG.md](https://github.com/artberri/sidr/blob/master/CHANGELOG.md)
