### ISSUE TITLE
Touch screen open menu instead of scroll

### ISSUE THREAD

**Issue by PixelT** [artberri/sidr#287]
On mobile web version, when I touch the screen to scroll the site down, instead of scroll the site to up / down - the menu is open (when I touch exactly on the button or element, which by default should open menu)

**Comment by artberri** [comment]
@PixelT This is because I'm trying to apply [fastclick](https://github.com/ftlabs/fastclick), so I'm not waiting the 300ms to trigger the click event, the menu is faster in this way. A side-effect is that every time you touch the open button, it opens the menu, it doesn't wait to know if you are clicking or sliding.

Maybe I will make a new option so you can indicate which event will trigger the menu. In that way you will be able to choose between being fast or accurate.

**Comment by artberri** [comment]
Well, now it's done. You can use the new version 2.2.0 and do the following:

You can change the button behavior, when you are creating the menu you can pass the option bind: `bind: 'click'`, in that way you will disable the **fastclick** and you won't have that problem.

**Comment by PixelT** [comment]
@artberri thanks!
