### ISSUE TITLE
A way to avoid scrollbars

### ISSUE THREAD

**Issue by althekiller** [artberri/sidr#295]
Is there any way to avoid scrollbars on desktops when the content of my sidr are taller than the viewport?  I'd be happy if it either scrolled with the entire page/body, or just didn't have its own scrollbars.  As of now, its taking me back to the days of frames in websites, since it's displaying a scrollbar on the left side sidr and another scrollbar on the body content.

**Comment by althekiller** [comment]
To further clarify a bit, what I'm wondering is is there a simple way to just have the off canvas portion the slides/overlaps in just scroll with the entire page as opposed to being fixed and limited by the height of the viewport?  (I've already moved my close menu button to within the menu itself, so regardless of scrolling it should be easy to close.)

**Comment by GarethAlinedCreativeDesign** [comment]
Add overflow:visible to the element with a scrollbar.

**Comment by artberri** [comment]
Sorry for being late answering. Stackoverflow is better for doubts. You could customize it with a custom scrollbar library or probably do it with CSS + the Sidr API, something like: 

overflow-y: visible;
position: absolute;
height: auto;
left: -260px;

This will not be added as a feature because it generates complexity and can be handle outside Sidr.
